### ISSUE TITLE
Hey there

### ISSUE THREAD

**Issue by 0xae** [PDP-10/-READ--THIS-#1]
Hii my name is ayrton. i always heard about PDP and recently i grew an imense interest on it.
* can i buy it somewhere (by the way i live in cape verde) i searched for it on ebay but could not find anything.
** i also though about simulators but i really wish i could program the real thing.

* can you give me some more hints about places where i could discover more things & such.
** would be cool to be in this group also although i never owned a PDP before :(   

* my interest on PDP grew exponentially after i discover FORTH and polyFORTH and the systems that AVD and Forth INC built with it on some huge airport

thank you

**Comment by larsbrinkhoff** [comment]
Hello,

From you comment I suppose your interest is with the PDP-11.  I believe Forth was most popular on that PDP series.

The PDP-11 is a 16-bit minicomputer.  This group is about the PDP-10, which is a 36-bit mainframe.  There's also the PDP-8, which is a 12-bit mini, and the PDP-1/4/7/9/15 18-bit computers.

If you want to buy a PDP-11, you can probably find some on ebay.  If you want to discuss Forth, check out the [ForthHub](http://github.com/ForthHub) organization.

Good luck!
