### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by jeffpar** [PDP-10/-READ--THIS-#10]
I'm definitely enthusiastic about the PDP-10, learning the architecture for the first time, and building a [browser-based simulation](http://www.pcjs.org/blog/) as I go.

**Comment by larsbrinkhoff** [comment]
Invitation sent.  Welcome!

What do you think about this? http://www.saildart.org/j5/index.html

Is it a PDP-10 emulator in JavaScript, or something else?

**Comment by jeffpar** [comment]
Thanks. And yes, there does appear to be a real PDP-10 emulator written in JavaScript buried there. it contains a lot of interesting comments that bear further reading, but the code is not pretty and contains a lot of incomplete operations (e.g., missing flag updates) and assorted kludges. It implements double-length rotates and shifts using strings of binary digits, for example--ouch.

I'm working pretty meticulously through the original PDP-10 manual, and writing the opcode handlers in native JavaScript from scratch, so hopefully the end result will be easier to understand and maintain.
