### ISSUE TITLE
Interested to join

### ISSUE THREAD

**Issue by krytarowski** [PDP-10/-READ--THIS-#12]
I'm interested in PDP-10 architecture.

Poland

**Comment by krytarowski** [comment]
In dreams I'm interested in LLVM backend for PDP-10 and NetBSD port to it.

In real world I will try with VAX backend in LLVM first.

Currently I'm involved in LLVM hacking on NetBSD, with stress on LLDB/NetBSD.

**Comment by larsbrinkhoff** [comment]
Hello,

I have sent an invitation; welcome!

Anders Magnusson has tried to port NetBSD to the PDP-10.  First he used my version of GCC, but later he swiched to use PCC instead.

**Comment by krytarowski** [comment]
The longer story is that he gave up with GCC and worked on PCC. There was initial success but as a mostly a one-man-show project he effectively run out of time to work on this compiler. After the years PCC just managed to build functional NetBSD kernel more or less for x86 and vax. Anders is vax port maintainer in NetBSD but also inactive over recent years.

NetBSD/PDP10 is/was a project goal to get it ported to a 36-bit platform (there was an alternative approach with risc36). But without a modern toolchain we are nowhere. GCC is effectively unfriendly for no-GNU contributions and no-GNU plaforms, and while LLVM is more liberal "free" it's a way to go.
