### ISSUE TITLE
Interested to join

### ISSUE THREAD

**Issue by jguillaumes** [PDP-10/-READ--THIS-#13]
Hello,

My name is Jordi Guillaumes, and I'm interested (as hobbyist) in running old machines and operating systems. I've done some contributions to SIMH (specifically, I made some fixes to the card reader software, and I rewrote the timing support of the pdp-10 simulator so the TOPS-10 monitor reports correct execution and cpu times), and I have permanently running a bunch of (virtual) VAXen, PDP11 and PDP10 systems.

**Comment by larsbrinkhoff** [comment]
Hello,

You are already in the PDP-10 organization!

**Comment by jguillaumes** [comment]
Thanks!
