### ISSUE TITLE
Invitation request

### ISSUE THREAD

**Issue by blipvert** [PDP-10/-READ--THIS-#14]
I apologize for having missed the previous invitation I was sent to this group.  I would like to be re-invited if possible.  Thank you.

**Comment by larsbrinkhoff** [comment]
Done!

**Comment by larsbrinkhoff** [comment]
And thank you for providing files and instructions for building ITS.  The ITS repository here was built up from that foundation.

**Comment by ams** [comment]
Taking the liberty to close this. ;-)

**Comment by larsbrinkhoff** [comment]
Hello @blipvert,

Would you consider linking to http://github.com/PDP-10/its from https://www.cosmic.com/u/mirian/its.html?
