### ISSUE TITLE
Request invite

### ISSUE THREAD

**Issue by thePastor** [PDP-10/-READ--THIS-#22]
Hi, I'm Mark Janssen.  I'm interested in the old DEC stuff and wish the old days were back (I was only on a VAX 685/11 --not too old).  Nothing has beaten VMS and VT terminals for exciting times.  The Javascript flybois haven't even come close to understanding the tools they're using.  Anyway, thanks!

**Comment by larsbrinkhoff** [comment]
Invitation sent.  Welcome!

VMS, eh?  I'll send NIL your way if I find it.
