### ISSUE TITLE
Invite me, please

### ISSUE THREAD

**Issue by david-bakin** [PDP-10/-READ--THIS-#24]
Used a KA10 in college (Harvey Mudd) in the mid-70s.  In fact, I was a "night operator" for several years as a part-time job while in school (hanging DECtapes, splitting printer output). It still is my favorite ISA ever.

(Oh I wish I wish I wish I still had my tapes of software.  But even had I kept them they'd be unreadable now ...)

**Comment by larsbrinkhoff** [comment]
Invitation sent.  You should be able to accept it here: http://github.com/PDP-10

Welcome!  Here we have a mix of users of TOPS-10, TOPS-20, and ITS.

**Comment by ZoBoRf** [comment]
I'd like to join.

**Comment by larsbrinkhoff** [comment]
Invitation sent; it should be visible here: http://github.com/PDP-10, or in an email.
