### ISSUE TITLE
I would like to join

### ISSUE THREAD

**Issue by mrihtar** [PDP-10/-READ--THIS-#28]
I was sysadmin for several years on our University Computer Center's DEC-10. A small contribution from me from that time: https://github.com/mrihtar/SuperPI-for-TOPS-10

**Comment by larsbrinkhoff** [comment]
Invitation sent.  Welcome!

There is now a wide selection of emulator for running TOPS-10: KA10, KI10, KL10 model B, and KS10.

**Comment by larsbrinkhoff** [comment]
Here is an ITS program to compute π

https://github.com/PDP-10/its/blob/master/src/rwg/ran.37

**Comment by mrihtar** [comment]
Thanks, joined. The ITS program for π looks kind of complicated ;-)
