### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by sharpjs** [PDP-10/-READ--THIS-#31]
I'd like to join.

Currently, I have no code to contribute and eleventy other projects in to-do status.  That said, I _do_ have a T-shirt design (SVG) I'd like to open-source, if that's sufficient to be welcomed into the fold.  You might vaguely remember me as `icbm` on IRC, or as a rando you met at VCF PNW 2019.

Thanks!

![PDP-10 Shirt](https://user-images.githubusercontent.com/708461/78587888-8a0b2a80-77f2-11ea-96b6-7d40aa06cc66.jpg)

**Comment by larsbrinkhoff** [comment]
Of course I remember.  Welcome!

**Comment by larsbrinkhoff** [comment]
As long as we're discussing shirts, here's mine.
![tshirt10](https://user-images.githubusercontent.com/775050/78593127-6a9ded00-7846-11ea-8b0f-e51371414e95.jpg)

**Comment by larsbrinkhoff** [comment]
@sharpjs, you seem to be familiar with a niche operating system called Windows.  The growing PDP-10 emulator family (which includes terminals, displays, gaming devices, etc) is mostly supported for running on Linux.  If you could advice on getting them running Windows, that would be great help.

Maybe use Cygwin?

**Comment by larsbrinkhoff** [comment]
Looks like building on Windows will not work:

```
$ git clone --depth=50 --branch=lars/cygwin https://github.com/PDP-10/its.git PDP-10/its
Cloning into 'PDP-10/its'...
error: invalid path 'bin/emacs/einit.:ej'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

I'm guessing it's the colon that's the problem.  On another machine I tried I had problems with filenames including * and ?.

**Comment by sharpjs** [comment]
Just noticed the additional comments on this.  Yep, my day job uses the Microsoft platform, but I'm comfortable in *nix as well.  I have not attempted to run any PDP-10 emulator on Windows yet.  If there are filenames that are invalid under Windows, then you're going to have a bad time, as you've discovered.  My suggestion for a way forward would be to use WSL (Windows Subsystem for Linux) or the currently-in-preview WSL2 to run them.  I'm about to try WSL2 (for other reasons) myself.

**Comment by larsbrinkhoff** [comment]
FYI, I tested the KA10 emulator on Cygwin and it runs well if you download the finished disk images.  It wouldn't run the ITS build script.
