### ISSUE TITLE
Stacken tape and games tapes

### ISSUE THREAD

**Issue by cbmira01** [PDP-10/-READ--THIS-#35]
Lars, or to whom it may concern...

Some years ago I snagged a tape from the Stacken club FTP site. It appeared to have some
developer utilities, including a DIFF utility:
https://drive.google.com/file/d/1dZeN-hka4JhjqhLNeDGYRePY9dTuL-Mr/view?usp=sharing

Also, I found these games tapes some time ago:
https://drive.google.com/file/d/1jjPeOMDy2zIuk7XSFlxMdfXulOTEuiY8/view?usp=sharing

I concentrated my collecting around TOPS-10 and PDP-10. If these tapes check out as 
useful, maybe they can join the collection here. 

Thanks,

- Calvin Miracle, cbmira01@gmail.com

**Comment by larsbrinkhoff** [comment]
Thank you.  This could be a great addition.

**Comment by larsbrinkhoff** [comment]
I created https://github.com/PDP-10/stacken
