### ISSUE TITLE
Scanning CHM documents

### ISSUE THREAD

**Issue by aap** [PDP-10/-READ--THIS-#6]
The CHM (http://www.computerhistory.org/) has a collection of PDP-6 and -10 related documents. I'm in contact now with Sydney Gulbronson who is responsible for scanning these things and she told me that they charge $1 per page, which can amount to quite a lot of money.

The PDP-6 related documents are these:
http://www.computerhistory.org/collections/catalog/102683300
http://www.computerhistory.org/collections/catalog/102683302
http://www.computerhistory.org/collections/catalog/10267943 (duplicate it seems)
http://www.computerhistory.org/collections/catalog/102750037
http://www.computerhistory.org/collections/catalog/102750036
http://www.computerhistory.org/collections/catalog/102679428
http://www.computerhistory.org/collections/catalog/102679431
http://www.computerhistory.org/collections/catalog/102683333

Source code of Spacewar!:
http://www.computerhistory.org/collections/catalog/102680667

Since it's not clear what some of the documents even are or how many pages they have I will ask about a few of them just see what price range we're looking at here.

The reason I'm posting this is of course to ask for money. I'm not exactly keen on spending hundreds of dollars on some scans that happen to not be on bitsavers. So if you're willing to spend some money on this or have a better idea how to have these digitized, please tell.

**Comment by larsbrinkhoff** [comment]
I would suggest talking to Al Kossow.  He's not only the master bitsaver, he's also a curator at CHM.

**Comment by aap** [comment]
I mailed him a while ago but he didn't reply to most of my email. He even ignored the scanned MACRO-6 manual I sent him :/

**Comment by larsbrinkhoff** [comment]
If messages are dropped, you may have to reroute them.  If e.g. Greenblatt asked for PDP-6 pdfs, maybe it'll get done quicker.

**Comment by larsbrinkhoff** [comment]
Related to this, there are many interesting articles at the ACM:  
https://www.google.com/search?q=site%3Aasm.org+%22pdp10%22  
https://www.google.com/search?q=site%3Aasm.org+%22pdp-10%22  
etc...

They are also behind a paywall.  Do ACM members get a discount?

**Comment by aap** [comment]
I could try from the uni network. I think I got some ACM articles before...some may be duplicates of AI memos or similar btw.

**Comment by aap** [comment]
PING @kossow. Please consider scanning more PDP-6 documents! And also please put the MACRO-6 manual on bitsavers:
http://pdp-6.net/docs/DEC-6-0-TP-MAC-LM-FP-ACT01_MACRO-6_Assembly_Language_Feb65.pdf

**Comment by aap** [comment]
I just noticed a bunch of new pdfs are now on bitsavers. Thanks a lot!!

**Comment by larsbrinkhoff** [comment]
See?  A combination of patience, persistence, and some more patience usually does the trick.

**Comment by kossow** [comment]
On 2/8/17 11:05 AM, Lars Brinkhoff wrote:
> See? A combination of patience, persistence, and some more patience usually does the trick.
>

once

don't try it again.

**Comment by larsbrinkhoff** [comment]
Case closed?

**Comment by aap** [comment]
For now :)
