### ISSUE TITLE
I'd like to join

### ISSUE THREAD

**Issue by dabridgham** [PDP-10/-READ--THIS-#7]
I'm new to git and GitHub but seeing your work here caused me to finally get an account.  I've been slowly working on a PDP-10 in an FPGA for a while now after the pattern of Dave Conroy's work.  It's running most of the processor diagnostics in simulation but I got distracted with another project so I don't think I'll have it running ITS for the 50th anniversary of the KA.

**Comment by larsbrinkhoff** [comment]
You're welcome!

So now I've heard of six FPGA implementations in total:
- XKL-1
- XKL-2
- Neil Franklin's [unfinished project](http://neil.franklin.ch/Projects/PDP-10/)
- Dave Conroy's [PDP-10/X](http://www.fpgaretrocomputing.org/pdp10x/)
- @jfcl's [KS10FPGA](https://github.com/KS10FPGA/KS10FPGA)
- Your work.

**Comment by aap** [comment]
Don't forget my fpdpga-6! (not quite a 10, but whatever) https://github.com/aap/pdp6

**Comment by dabridgham** [comment]
Definitely I'd include the PDP-6 in the list.

**Comment by larsbrinkhoff** [comment]
Sorry, there's just too many for me to keep track of!

**Comment by larsbrinkhoff** [comment]
Reimplementing the 10 has been a fun hack for ages:

- MAXC from Xerox
- SC-20/25/30/40 from Systems Concepts
- F-1/2/3/4/5 from Foonly
- System 26 from Tymshare
- XKL-1/2 from XKL

**Comment by aap** [comment]
We should found our own company and make 10s! I want a PDP-10 laptop with a Knight TV as display...or maybe a Raspberry PDP :D

**Comment by larsbrinkhoff** [comment]
The people behind the PiDP-8 are supposedly making a PDP-11 replica.  The logical progression would be to make a 10 next.  I'd so be all over that!

**Comment by aap** [comment]
Yup, I saw Oscar's PiDP-11 in November at VFCE CH (Jörg Hoppe and I even stayed at his place). He certainly wants to make a PDP-10 panel replica, but it will still take a while before he can tackle that...he hasn't even decided whether he wants to do a KA or KI panel. We'll see...

**Comment by larsbrinkhoff** [comment]
Maybe we should list the software implementations as well:

- S. W. Galley's [virtual machine PDP-10](http://dl.acm.org/citation.cfm?id=803947)
- Megan Gentry's sim10
- Stu Grossman's [KX10](http://github.com/brouhaha/kx10)
- Ken Harrenstien's [KLH10](http://github.com/PDP-10/klh10)
- @brouhaha was rumored to have started one.
- @dseagrav's e10 (I've seen this on ftp servers)
- @FSword7's [TS10](https://sourceforge.net/projects/ts10/).
- @archivisth's [SIMH](http://github.com/simh/simh).

**Comment by larsbrinkhoff** [comment]
Rumor has it cisco tried to make a clone as well.

**Comment by aap** [comment]
That's what Johnny Billquist told me anyway. They wanted to make PDP-10 clones but first needed to get some money by selling network gear. Later the same people founded XKL and ended up with network gear as well.

**Comment by dabridgham** [comment]
I *have* thought about adding a Knight TV once the -10 is running. 
Either that or a 340 display for Spacewar.  Thing is, I've never
actually seen a Knight TV and haven't found any documentation for the
things so I'm not entirely sure what I'd be building.

I'd love to see what Oscar comes up with for a PDP-10 replica console
panel for a PiDP-10.  You can see on my website what my thinking has
been for a console for my KV10.  I wanted it to be reminiscent of the
KI10 but in trying to keep costs under control it's built with
capacitive touch switches and it's shrunk down so it could fit in a 19"
inch rack.  My general approach is that I'm not trying to build a
replica of any particular -10 but rather just build a new implementation
of the -10 architecture.  I intend for it to have an optional serial or
USB interface so it could use used with a software PDP-10 emulation as well.

**Comment by larsbrinkhoff** [comment]
Here's what we know about the Knight TV so far:
https://github.com/PDP-10/its/issues/279

**Comment by dabridgham** [comment]
Looks like a bit of archeology will be involved with recreating any
Knight TVs.  I'll just focus for now on getting my PDP-10 working. 
Well, and the QSIC first which what has pushed the KV10 project to the
back burner at the moment.

**Comment by jfcl** [comment]
On 1/20/2017 5:49 AM, David Bridgham wrote:
> I *have* thought about adding a Knight TV once the -10 is running.
> Either that or a 340 display for Spacewar.

There was a 340 display attached to the Penn State KA10.

I used a schematic capture program that used the 340 display.  I tended 
to use it mostly off-hours because it was unusable when the system was 
busy.  It might have been a 339 display.

Rob.

**Comment by larsbrinkhoff** [comment]
Wouldn't it be *awesome* if there were a replica PDP-10 connected to a replica PDP-11 controlling a replica Knight TV?  I'm swooning.

**Comment by aap** [comment]
We should definitely do this. But it'll take some time :)

**Comment by dabridgham** [comment]
I like the way you think, Lars.  As I work on the [QSIC](https://github.com/dabridgham/QSIC), I can't help but think how little a change to the hardware it would take for the board to be able to act as a processor card as well as the purpose we're intending for it.  Want to put a PDP-10 on the QBUS?

**Comment by larsbrinkhoff** [comment]
Of course I'd like to put PDP-10s everywhere.  But for now, I run a strictly software-only shop here at home, so no pressing need for QBUS.

**Comment by larsbrinkhoff** [comment]
[Quoth Alderson](https://hardware.slashdot.org/comments.pl?sid=10009&cid=500361):

> Len wanted to build a TOAD ("10 on a desktop") in the 70's, when he worked for DEC; cisco Systems' original business plan was to do just that.

**Comment by larsbrinkhoff** [comment]
@obsolescence is completing his PDP-11 replica right about now, and says he's planning to do a KA10.

Need to get back to working with @rcornwell to ensure the SIMH KA10 can run ITS!

**Comment by rcornwell** [comment]
Lars you forgot to mention my KA10/KI10 sim in your list of software sims. Also mine originally started life as a prototype for a FPGA implementation. 

Right now I am cleaning up bugs in my Ibm 7000 simulators to get them moved into the main tree. However if you want to generate some test images and tell me where they are breaking I will fix any bugs. 

Someone might be doing a software front panel for my KA10/KI10 in the near future also.

**Comment by larsbrinkhoff** [comment]
Sorry, I'll add it to the list!  Always happy to see more. :-)
